//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreciPoint.Ims.Services.Annotation.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PreciPoint.Ims.Services.Annotation.Localization.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation &apos;{0}&apos; cannot add coordinate because is of type &apos;{1}&apos;.
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_CANNOT_ADD_COORDINATE {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.CANNOT_ADD_COORDINATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  User with ID &apos;{0}&apos; is not allowed to delete Annotation &apos;{1}&apos;..
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_CANNOT_DELETE {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.CANNOT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation &apos;{0}&apos; cannot delete coordinate because is of type &apos;{1}&apos;.
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_CANNOT_DELETE_COORDINATE {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.CANNOT_DELETE_COORDINATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation &apos;{0}&apos; of type &apos;{1}&apos; cannot have counting because it&apos;s not a closed shape..
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_CANNOT_HAVE_COUNTERS {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.CANNOT_HAVE_COUNTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Annotation is {0}. User with ID &apos;{1}&apos; is not allowed to manage Annotation &apos;{2}&apos;..
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_CANNOT_MANAGE {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.CANNOT_MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation &apos;{0}&apos; cannot set radius because is of type &apos;{1}&apos;.
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_CANNOT_SET_RADIUS {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.CANNOT_SET_RADIUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation with ID &apos;{0}&apos; is not a Circle but is a &apos;{1}&apos;..
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_CIRCLE_TYPE_MISMATCH {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.CIRCLE_TYPE_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates cannot be null or empty..
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_COORDINATE_NULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.COORDINATE_NULL_OR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Forbidden. Annotation &apos;{0}&apos; of type &apos;{1}&apos; does not contains the counter ({2},{3}) and id &apos;{4}&apos;.
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_COUNTERS_NOT_CONTAINED {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.COUNTERS.NOT_CONTAINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert at least one point with coordinates, make sure that X and Y arrays have the same length..
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_EMPTY_COORDINATE_LIST {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.EMPTY_COORDINATE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plese insert at least one ID..
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_EMPTY_LIST {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.EMPTY_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation of type &apos;{0}&apos; must have first and last element with same coordinates. first is ({1},{2}) and last is ({3},{4})..
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_FIRST_AND_LAST_MISMATCH {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.FIRST_AND_LAST_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during persistence of data from .vpa file. Transaction was rolled back..
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_IMPORT_VPA_PERSISTENCE {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.IMPORT_VPA.PERSISTENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation of type &apos;{0}&apos; need {1} coordinates..
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_NEED_MULTI_COORDINATE {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.NEED_MULTI_COORDINATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation of type &apos;{0}&apos; need one coordinate..
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_NEED_ONE_COORDINATE {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.NEED_ONE_COORDINATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation with ID &apos;{0}&apos; was not found..
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_NOT_FOUND {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The annotation ID cannot be null..
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_NOT_NULL_ID {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.NOT_NULL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during SYNCHRONIZATION. Transaction was rolled back..
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_SYNCHRONIZE {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.SYNCHRONIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to perform this action..
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_UNAUTHORIZED {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; requested to update annotation. But Annotation ID &apos;{1}&apos; and Slide Image ID &apos;{2}&apos; combination was not found..
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_WRONG_COMBO_ID_AND_SLIDEIMAGE_ID {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.WRONG_COMBO_ID_AND_SLIDEIMAGE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation &apos;{0}&apos; of type &apos;{1}&apos; cannot use index equals to &apos;{2}&apos;, it must be contained in (0 and {3}) range..
        /// </summary>
        public static string APPLICATION_ANNOTATIONS_WRONG_INDEX {
            get {
                return ResourceManager.GetString("APPLICATION.ANNOTATIONS.WRONG_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided color format is invalid, because it is composed of {0} values. Color can only be composed of 3 (RGB) or 4 (RGBA) values..
        /// </summary>
        public static string APPLICATION_COLOR_FORMAT_INVALID {
            get {
                return ResourceManager.GetString("APPLICATION.COLOR_FORMAT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided color value {0} is out of range of the allowed Color range (0-255)..
        /// </summary>
        public static string APPLICATION_COLOR_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("APPLICATION.COLOR_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Group with ID &apos;{0}&apos; was not found..
        /// </summary>
        public static string APPLICATION_COUNTERGROUPS_NOT_FOUND {
            get {
                return ResourceManager.GetString("APPLICATION.COUNTERGROUPS.NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The counter group ID cannot be null..
        /// </summary>
        public static string APPLICATION_COUNTERGROUPS_NOT_NULL_ID {
            get {
                return ResourceManager.GetString("APPLICATION.COUNTERGROUPS.NOT_NULL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter with ID &apos;{0}&apos; was not found..
        /// </summary>
        public static string APPLICATION_COUNTERS_NOT_FOUND {
            get {
                return ResourceManager.GetString("APPLICATION.COUNTERS.NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Image with ID &apos;{0}&apos; was not found..
        /// </summary>
        public static string APPLICATION_SLIDE_IMAGES_NOT_FOUND {
            get {
                return ResourceManager.GetString("APPLICATION.SLIDE_IMAGES.NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown server error happened. Please try again later..
        /// </summary>
        public static string CORE_MIDDLEWARES_INTERNAL_SERVER_ERROR {
            get {
                return ResourceManager.GetString("CORE.MIDDLEWARES.INTERNAL_SERVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s an error with your security configuration. We&apos;re unable to examine who you are..
        /// </summary>
        public static string CORE_MIDDLEWARES_UNAUTHORIZED {
            get {
                return ResourceManager.GetString("CORE.MIDDLEWARES.UNAUTHORIZED", resourceCulture);
            }
        }
    }
}
