using System.Collections.Generic;
using System.Xml.Serialization;

#pragma warning disable CS1591

namespace PreciPoint.Ims.Services.Annotation.Application.Infrastructure.VPA;

/// <summary>
/// Autogenerated class that maps the vpa xml file structure
/// </summary>
[XmlRoot(ElementName = "Annotations")]
public class AnnotationsVpaMapping
{
    [XmlElement(ElementName = "Rectangles")]
    public Rectangles Rectangles { get; set; }

    [XmlElement(ElementName = "Markers")]
    public Markers Markers { get; set; }

    [XmlElement(ElementName = "Lines")]
    public Lines Lines { get; set; }

    [XmlElement(ElementName = "Circles")]
    public Circles Circles { get; set; }

    [XmlElement(ElementName = "Polygons")]
    public Polygons Polygons { get; set; }

    [XmlElement(ElementName = "Polylines")]
    public Polylines Polylines { get; set; }

    [XmlElement(ElementName = "Countings")]
    public Countings Countings { get; set; }
}

[XmlRoot(ElementName = "Rectangle")]
public class Rectangle
{
    [XmlElement(ElementName = "Points")]
    public string Points { get; set; }

    [XmlAttribute(AttributeName = "Description")]
    public string Description { get; set; }

    [XmlAttribute(AttributeName = "IsVisible")]
    public string IsVisible { get; set; }
}

[XmlRoot(ElementName = "Rectangles")]
public class Rectangles
{
    [XmlElement(ElementName = "Rectangle")]
    public List<Rectangle> Rectangle { get; set; }
}

[XmlRoot(ElementName = "Marker")]
public class Marker
{
    [XmlElement(ElementName = "Points")]
    public string Points { get; set; }

    [XmlAttribute(AttributeName = "Description")]
    public string Description { get; set; }

    [XmlAttribute(AttributeName = "IsVisible")]
    public string IsVisible { get; set; }
}

[XmlRoot(ElementName = "Markers")]
public class Markers
{
    [XmlElement(ElementName = "Marker")]
    public List<Marker> Marker { get; set; }
}

[XmlRoot(ElementName = "Line")]
public class Line
{
    [XmlElement(ElementName = "Points")]
    public string Points { get; set; }

    [XmlAttribute(AttributeName = "Description")]
    public string Description { get; set; }

    [XmlAttribute(AttributeName = "IsVisible")]
    public string IsVisible { get; set; }
}

[XmlRoot(ElementName = "Lines")]
public class Lines
{
    [XmlElement(ElementName = "Line")]
    public List<Line> Line { get; set; }
}

[XmlRoot(ElementName = "Circle")]
public class Circle
{
    [XmlElement(ElementName = "Points")]
    public string Points { get; set; }

    [XmlAttribute(AttributeName = "Description")]
    public string Description { get; set; }

    [XmlAttribute(AttributeName = "IsVisible")]
    public string IsVisible { get; set; }
}

[XmlRoot(ElementName = "Circles")]
public class Circles
{
    [XmlElement(ElementName = "Circle")]
    public List<Circle> Circle { get; set; }
}

[XmlRoot(ElementName = "Polygon")]
public class Polygon
{
    [XmlElement(ElementName = "Points")]
    public string Points { get; set; }

    [XmlAttribute(AttributeName = "Description")]
    public string Description { get; set; }

    [XmlAttribute(AttributeName = "IsVisible")]
    public string IsVisible { get; set; }
}

[XmlRoot(ElementName = "Polygons")]
public class Polygons
{
    [XmlElement(ElementName = "Polygon")]
    public List<Polygon> Polygon { get; set; }
}

[XmlRoot(ElementName = "Polyline")]
public class Polyline
{
    [XmlElement(ElementName = "Points")]
    public string Points { get; set; }

    [XmlAttribute(AttributeName = "Description")]
    public string Description { get; set; }

    [XmlAttribute(AttributeName = "IsVisible")]
    public string IsVisible { get; set; }
}

[XmlRoot(ElementName = "Polylines")]
public class Polylines
{
    [XmlElement(ElementName = "Polyline")]
    public List<Polyline> Polyline { get; set; }
}

[XmlRoot(ElementName = "Type")]
public class Type
{
    [XmlElement(ElementName = "Points")]
    public string Points { get; set; }

    [XmlAttribute(AttributeName = "Name")]
    public string Name { get; set; }
}

[XmlRoot(ElementName = "Species")]
public class Species
{
    [XmlElement(ElementName = "Type")]
    public List<Type> Type { get; set; }
}

[XmlRoot(ElementName = "Counting")]
public class Counting
{
    [XmlElement(ElementName = "Points")]
    public string Points { get; set; }

    [XmlElement(ElementName = "Species")]
    public Species Species { get; set; }

    [XmlAttribute(AttributeName = "Description")]
    public string Description { get; set; }

    [XmlAttribute(AttributeName = "IsVisible")]
    public string IsVisible { get; set; }
}

[XmlRoot(ElementName = "Countings")]
public class Countings
{
    [XmlElement(ElementName = "Counting")]
    public List<Counting> Counting { get; set; }
}