// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PreciPoint.Ims.Services.Annotation.Database;
using PreciPoint.Ims.Services.Annotation.Enums;

namespace PreciPoint.Ims.Services.Annotation.Database.Migrations
{
    [DbContext(typeof(AnnotationDbContext))]
    [Migration("20211112155255_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasPostgresEnum(null, "annotation_type", new[] { "point", "marker", "line", "circle", "rectangular", "polygon", "polyline", "grid" })
                .HasPostgresEnum(null, "annotation_visibility", new[] { "private", "public" })
                .HasPostgresExtension("postgis")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("PreciPoint.Ims.Services.Annotation.Domain.Model.AnnotationShape", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Uniquely identifies an Annotation.");

                    b.Property<int[]>("Color")
                        .HasColumnType("integer[]")
                        .HasComment("Contains color information information");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision")
                        .HasComment("Describe the confidence value of this annotation. used by AI and ML");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("Contains the user id that created the record");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Contains the creation date");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("The description of annotation");

                    b.Property<Guid?>("ImportId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasComment("Describe if the annotation is hidden.");

                    b.Property<string>("Label")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("The brief description of annotation");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("Contains the user id that modified the values");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Contains the modification date");

                    b.Property<Geometry>("Shape")
                        .IsRequired()
                        .HasColumnType("Geometry")
                        .HasComment("Contains geometry information");

                    b.Property<Guid>("SlideImageId")
                        .HasColumnType("uuid")
                        .HasComment("The unique identifier of a slide image");

                    b.Property<AnnotationType>("Type")
                        .HasColumnType("annotation_type")
                        .HasComment("Describe the annotation type. defined by it's coordinates");

                    b.Property<AnnotationVisibility>("Visibility")
                        .HasColumnType("annotation_visibility")
                        .HasComment("Describe the annotation visibility.");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ImportId");

                    b.HasIndex("Shape")
                        .HasMethod("GIST");

                    b.HasIndex("SlideImageId");

                    b.ToTable("Annotations", "ims");

                    b
                        .HasComment("Contains rows that define Annotations linked to a slide image.");
                });

            modelBuilder.Entity("PreciPoint.Ims.Services.Annotation.Domain.Model.Counter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Uniquely identifies a Counter");

                    b.Property<Guid>("GroupCounterId")
                        .HasColumnType("uuid");

                    b.Property<Geometry>("Shape")
                        .IsRequired()
                        .HasColumnType("geometry (point)")
                        .HasComment("Contains geometry information");

                    b.HasKey("Id");

                    b.HasIndex("GroupCounterId");

                    b.HasIndex("Shape")
                        .HasMethod("GIST");

                    b.ToTable("Counters", "ims");

                    b
                        .HasComment("Contains rows that define counters that belongs to a specific groups.");
                });

            modelBuilder.Entity("PreciPoint.Ims.Services.Annotation.Domain.Model.CounterGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Uniquely identifies a Counter Group.");

                    b.Property<Guid>("AnnotationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("Contains the user id that created the record");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Contains the creation date");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("The description of annotation");

                    b.Property<string>("Label")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("The brief description of annotation");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("Contains the user id that modified the values");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Contains the modification date");

                    b.HasKey("Id");

                    b.HasIndex("AnnotationId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("CounterGroups", "ims");

                    b
                        .HasComment("Contains rows that define counter groups linked to annotation.");
                });

            modelBuilder.Entity("PreciPoint.Ims.Services.Annotation.Domain.Model.Import", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Uniquely identifies an import.");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("Contains the user id that created the record");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Contains the creation date");

                    b.Property<byte[]>("File")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasComment("The file content");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("The file name");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasComment("Contains the user id that modified the values");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Contains the modification date");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Imports", "ims");

                    b
                        .HasComment("Contains rows that track all annotation imported with a specific file.");
                });

            modelBuilder.Entity("PreciPoint.Ims.Services.Annotation.Domain.Model.AnnotationShape", b =>
                {
                    b.HasOne("PreciPoint.Ims.Services.Annotation.Domain.Model.Import", "Import")
                        .WithMany("Annotations")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Import");
                });

            modelBuilder.Entity("PreciPoint.Ims.Services.Annotation.Domain.Model.Counter", b =>
                {
                    b.HasOne("PreciPoint.Ims.Services.Annotation.Domain.Model.CounterGroup", "CounterGroup")
                        .WithMany("Counters")
                        .HasForeignKey("GroupCounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CounterGroup");
                });

            modelBuilder.Entity("PreciPoint.Ims.Services.Annotation.Domain.Model.CounterGroup", b =>
                {
                    b.HasOne("PreciPoint.Ims.Services.Annotation.Domain.Model.AnnotationShape", "Annotation")
                        .WithMany("CounterGroups")
                        .HasForeignKey("AnnotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annotation");
                });

            modelBuilder.Entity("PreciPoint.Ims.Services.Annotation.Domain.Model.AnnotationShape", b =>
                {
                    b.Navigation("CounterGroups");
                });

            modelBuilder.Entity("PreciPoint.Ims.Services.Annotation.Domain.Model.CounterGroup", b =>
                {
                    b.Navigation("Counters");
                });

            modelBuilder.Entity("PreciPoint.Ims.Services.Annotation.Domain.Model.Import", b =>
                {
                    b.Navigation("Annotations");
                });
#pragma warning restore 612, 618
        }
    }
}
